name: 'Run MetaEditor Compiler'
description: 'Run MetaEditor Compiler'
author: 'Martijn Riemers'

inputs:
  version:
    description: 'Version of MetaEditor to use'
    required: false
    default: '4'
  files:
    description: 'Files to compile'
    required: true
  include:
    description: 'Additional directory to include for compilation'
    required: false

outputs:
  results:
    description: 'Compilation results for each compiled file'

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.version }}
    - ${{ inputs.files }}
    - ${{ inputs.include }}

branding:
  icon: 'bar-chart'
  color: 'green'
